/// Communes desservies par la plateforme (§8 du cahier des charges).
const kKinshasaCommunes = [
  'Gombe',
  'Lingwala',
  'Barumbu',
  'Kinshasa',
  'Kasa-Vubu',
  'Ngaliema',
  'Bandalungwa',
  'Kintambo',
  'Lemba',
  'Limete',
  'Matete',
  'Ndjili',
  'Masina',
  'Kimbanseke',
  'Mont-Ngafula',
  'Selembao',
  'Bumbu',
  'Makala',
  'Ngaba',
  'Kalamu',
  'Ngiri-Ngiri',
  'Nsele',
  'Maluku',
];
